package.json
yarn.lock

Adds jest-junit package, required for @artsy/yarn orb.

Add jest-junit package

---

src/Schema/ActionType.ts
src/Schema/Authentication.ts
src/Schema/Event.ts

1st PR! Eve will merge this PR for now, but in the future this is where the data team will discuss the new event schema being added and then someone on the data team will merge.
https://artsyproduct.atlassian.net/browse/PLATFORM-2305
https://artsyproduct.atlassian.net/browse/PLATFORM-2306

Adds createdAccount and successfullyLoggedIn to Schema

---

tsconfig.json

Turns on "strict" in typescript config.

Use typescript strict

---

src/Events/Tap/TappedEntityGroup.ts

add export for TappedEntityDestinationType

---

src/Events/Tap/TappedConsign.ts
src/Events/Tap/__tests__/TappedConsign.test.ts
src/Schema/Events/Tap.ts

Adds a helper to implement `tappedConsign` events in iOS.

Add tappedConsign helper

---

README.md

Cool repo pals!! 🙌
I noticed a broken link to the NPM package and then did a little more work on the links in the README, hope that's ok!! ❤️

Manage links in README

---

src/Events/System/__tests__/TimeOnPage.test.ts

add timeOnPage helper test

---

src/Schema/OwnerType.ts

Adding collect page as an owner type.

@eessex => [OwnerType] Add collect page

---

src/Schema/Events/Click.ts
src/Schema/Events/Tap.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/EntityModuleType.ts
src/Schema/Values/Intent.ts
src/Schema/Values/OwnerType.ts

Fixes links to point at correct helpers.

Cleanup docs links

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/Intent.ts

When implementing the signup modal for viewing rooms, looks like the existing pattern is to attach a ContextModule and Intent to the auth modal. Let me know if this is the right work flow!

GALL-2880 Add tracking for signing up due to viewing rooms

---

src/Schema/Events/Tap.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

[cc: @ashfurrow @brainbicycle]
Submitting analytics tracking for the home screen promo space on iOS. Comments within the code.
[[Jira](https://artsyproduct.atlassian.net/browse/MX-336)]

Track taps on the iOS promo space

---

src/Helpers/Tap/TappedPromoSpace.ts
src/Helpers/Tap/__tests__/TappedPromoSpace.test.ts

See conversation here: https://github.com/artsy/eigen/pull/3517/files#r448654900

Adds helper for promo space tap tracking

---

src/Schema/Values/ContextModule.ts

#trivial
Adds a context module for "Works from Galleries You Follow" rail on home feed in the iOS app.

Add contextModule for followed galleries rail

---

src/Schema/Events/Tap.ts
src/Schema/Events/index.ts

This adds tappedMainArtworkGrid for iOS.

Adds tappedMainArtworkGrid

---

src/Schema/Values/OwnerType.ts

Used by timeOnPage events in Force.

Add "artists" and "galleries" to OwnerType

---

src/Schema/Values/OwnerType.ts

Oops! Forgot I needed to do this.

Include artistSeries in ScreenOwnerType

---

src/Schema/Values/OwnerType.ts

Used for follow/unfollow events in Force.

Add article and articles to OwnerType

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

context_module and owner_type for the all artist series screen on iOS. slack thread here - https://artsy.slack.com/archives/C9SATFLUU/p1598447162147200

Adds allArtistSeries for iOS

---

src/Schema/Values/ContextModule.ts

Context Module for "Works by artist you follow" rail

Context Module for "Works by artist you follow" rail

---

src/Schema/Values/OwnerType.ts

This adds article and articles as a screen owner type.

Adds article screen owner type

---

src/Schema/Values/OwnerType.ts

We are adding a new artworks screenview for fairs. This adds a fairArtworks owner type.

Adds fairArtworks OwnerType for new screenview

---

src/Schema/Values/ContextModule.ts

In response to this PR - https://github.com/artsy/reaction/pull/3644#discussion_r498536618

Adds articleArtist contextModule

---

src/Schema/Events/Search.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

This PR adds new search events to cohesion + 1 context module needed for the new consign page.
See the /consign2 sheet here - https://docs.google.com/spreadsheets/d/12wj1rt-j5SguboPJMuaM1GqJD-5B5u5piipw8MQ5Zuk/edit#gid=0
@eessex I'm assigning you because I'd like to get your thoughts on this new search file!
@anipetrov let me know if you're good with these search events. They pretty much mirror the current search events for the main search bar, which are not in cohesion yet.

[AS-1656] Adds new search events

---

src/Schema/Values/ContextModule.ts

- adding this contextModule since this is a place from which you can tap 'register to bid'

Add context module for aboutThisAuction

---

src/Schema/Values/ContextModule.ts

- adds a context module for actions taken in the live auction room (such as tapping register to bid)

Add liveAuctionRoom context module

---

src/Helpers/Tap/TappedRegisterToBid.ts
src/Helpers/Tap/__tests__/TappedRegisterToBid.test copy.ts
src/Schema/Values/OwnerType.ts

- Added Tapped register to bid helper

feat: added tapped register to bid helper

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

This adds an event for when a user clicks an app download CTA. Need it for the consign page - https://www.figma.com/file/I7a7Iy3yCFi7Pj1VguqMFG/Sell-Art-Landing-%5BWeb%5D?node-id=1155%3A0

[AS-1689] Adds clickedAppDownload event

---

src/Schema/Values/OwnerType.ts

Add user to `OwnerType`/`PageOwnerType` - for user settings page.

#trivial: Add user to OwnerTypes

---

src/Schema/Events/MyCollection.ts
src/Schema/Events/Tap.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

- groups add, edit, delete and tap events for the My Collection flow
- adds contexts and owners for myCollection and myCollectionArtwork
- specs [here](https://www.figma.com/file/yDSHlbJVzBxvSUROD2bfRI/Sell-tab?node-id=1%3A2) and [here](https://www.figma.com/file/yDSHlbJVzBxvSUROD2bfRI/Sell-tab?node-id=466%3A24999)

Track critical myCollection events and contexts

---

src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts

- Tracking schema for taps to the artwork images on a myCollectionArtwork screen

Track taps on collected artwork images

---

src/Helpers/Click/ClickedMainArtworkGrid.ts
src/Helpers/Click/__tests__/ClickedMainArtworkGrid.test.ts
src/Schema/Events/Click.ts

Re: [FX-2545](https://artsyproduct.atlassian.net/browse/FX-2545)

feat: adds position and sort args to artwork click

---

src/Helpers/Tap/TappedMainArtworkGrid.ts
src/Helpers/Tap/__tests__/TappedMainArtworkGrid.test.ts
src/Schema/Events/Tap.ts

Re: [FX-2550](https://artsyproduct.atlassian.net/browse/FX-2550)

feat: adds position and sort args to artwork tap

---

src/Helpers/Tap/TappedInfoBubble.ts
src/Schema/Events/Tap.ts

- Add `auctionResultSalePrice` as subject `TappedInfoBubble.ts`

feat: add auctionResultSalePrice

---

src/Schema/Values/ContextModule.ts

- Add auction result context modules

feat: add auction result context modules

---

src/Schema/Values/OwnerType.ts

I forgot to add the `onboarding` owner type so here it is!

Adds onboarding owner type

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

Adds CMS Checklist Events and toDoList context module.
- Added new Context Module: toDoList
- Added following Click events: ClickedEditArtwork, ClickedSnooze, ClickedExpandArrow, ClickedCollapseArrow, ClickedLoadMore
[New Checklist design for reference ](https://www.figma.com/file/N0Xh5DaHaXo8q72a5FtVWh/CMS-Checklist?node-id=128%3A0)

[AS-1940] New Checklist Events in Cohesion 

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

The type of this PR is: Enhancement
This PR resolves [PX-3846]
This PR updates naming and examples for events we expect CMS checklist to consume.
[PX-3846]: https://artsyproduct.atlassian.net/browse/PX-3846

Chore(PX-3846): Clicked[Expand|Collapse]Arrow -> ClickedExpansionToggle

---

src/Helpers/Tap/TappedTabBar.ts
src/Helpers/Tap/__tests__/TappedTabBar.test.ts
src/Schema/Values/OwnerType.ts

This PR resolves [CX-862]
[CX-862]: https://artsyproduct.atlassian.net/browse/CX-862

[WIP] feat: add tracking contextScreenOwnerType

---

src/Helpers/Tap/TappedEntityGroup.ts

This PR resolves [CX-1550]
[CX-1550]: https://artsyproduct.atlassian.net/browse/CX-1550

feat: Add articles screen tab destination types

---

src/Schema/Values/ContextModule.ts

This PR resolves [CX-1550]
[CX-1550]: https://artsyproduct.atlassian.net/browse/CX-1550

feat: Add articles context module

---

src/Schema/Events/System.ts

The type of this PR is: **documentation**
This PR resolves [AS-2163].
@pvinis Just adding a comment, this was a straggler from before I went on leave. Let me know if this should be better-clarified. 
[AS-2163]: https://artsyproduct.atlassian.net/browse/AS-2163

Helpful comment about screen vs track API calls

---

src/Schema/Values/ContextModule.ts

This PR resolves [CX-1617]
Added context for AuctionResultsForArtistsYouFollow
[CX-1617]: https://artsyproduct.atlassian.net/browse/CX-1617

feat: Add AuctionResultsForArtistsYouFollow context module

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

This PR resolves [CX-1617]
Add auctionResultsForArtistsYouFollow to OwnerType.ts
[CX-1617]: https://artsyproduct.atlassian.net/browse/CX-1617

feat: add auctionResultsForArtistsYouFollow to OwnerType.ts

---

src/Helpers/Conversations/TappedConfirmArtwork.ts
src/Schema/Events/Conversations.ts

This PR resolves [PURCHASE-2801]https://artsyproduct.atlassian.net/browse/PURCHASE-2801
Updates schema to reflect make offer in inquiry tracking: https://docs.google.com/spreadsheets/d/1NIzJ8jQ1BzGxDDmB0pYWjsmfCk3GRRgxtmjTJV1zWg0/edit#gid=0
[PURCHASE-2801]: https://artsyproduct.atlassian.net/browse/PURCHASE-2801

chore: updates schema and tracking method for inquiry make offer screen

---

src/Schema/Values/ContextModule.ts

The type of this PR is: Enhancement 
JIRA [GRO-408]
This is to support the incoming change in Force for the Curatorial Rails in Auction, New TrendingLots and StandoutLots Rails going in.
[GRO-408]: https://artsyproduct.atlassian.net/browse/GRO-408

Added in trending Lots and standoutlots

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/Intent.ts

Follow fair organizer Sign up modal Context module

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

This PR adds specific event for framed dimensions dropdown menus. 
**EDIT:**
It also includes some name changes to framed dimensions events to better align with the UI/database.

[PX-4220] - Track analytics for weight & framed dimensions in CMS

---

src/Schema/Events/FilterAndSort.ts
src/Schema/Events/Search.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

Schema for events on the new Price Database experience for web. Wireframes [here](https://www.figma.com/file/4fxnvYKVZzBr3TEE6WBj2J/Price-Database-%2F-Q3-2021?node-id=1226%3A8174) and comments in-line.

Schema for Price Database web events

---

src/Schema/Values/OwnerType.ts

Saved Search Owner type

---

src/Schema/Values/ContextModule.ts

Booth tab context module

---

src/Schema/Values/OwnerType.ts

chore: add saved searches owner type

---

.github/depdendabot.yml

Adds the default dependabot config and sets the platform team as the
maintainers.

feature: Configure Dependabot Alerts

---

renovate.json

The type of this PR is: **Documentation**
Updates the renovate user.

chore: Update Renovate User

---

src/Schema/Events/Authentication.ts

This PR resolves [CX-1663]
This PR adds google as an `AuthService`.
[CX-1663]: https://artsyproduct.atlassian.net/browse/CX-1663

feat: add google as auth service

---

src/DeprecatedHelpers/Authentication/CreatedAccount.ts
src/DeprecatedHelpers/Authentication/ResetYourPassword.ts
src/DeprecatedHelpers/Authentication/SuccessfullyLoggedIn.ts
src/Schema/Values/ContextModule.ts

This PR corrects and adds a few things to support https://github.com/artsy/force/pull/8483

Fixes to types for new inquiry

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

Addresses [CX-2001]
Adds newWorksForYouRail context module and owner type.
[CX-2001]: https://artsyproduct.atlassian.net/browse/CX-2001

feat: Add newWorksForYouRail context module and owner type

---

src/Schema/Events/Consignments.ts
src/Schema/Events/index.ts

We use this event in our pipeline to associate sessions to consignment submissions.
- [ x] If I've added a new file to the tree I've exported it from the common `index.ts`
- [ x] I've added comments with examples for any new interfaces and ensured that they're in the docs
- [ x] No platform-specific terminology has been used outside of `click` and `tap` (platform is inferred by the DB storing events)

Adds consignmentSubmitted event

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

This PR resolves [CX-2125]
Added ordersSubmitted
[CX-2125]: https://artsyproduct.atlassian.net/browse/CX-2125?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Added order submitted

---

src/Schema/Values/ContextModule.ts

This PR resolves [CX-942]
Added tracking for comparable works in auction result
[CX-942]: https://artsyproduct.atlassian.net/browse/CX-942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Added auction result comparable works

---

src/Schema/Events/Click.ts
src/Schema/Events/Toggle.ts
src/Schema/Events/index.ts

Analytics tracking for web alerts.

Web Alert events

---

src/Schema/Events/Conversations.ts
src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

Add my collection add artwork add artist screen events

feat: Add my collection add artwork events

---

src/Schema/Values/ContextModule.ts

Addresses [CX-2368]
Add myCollectionComparableWorks context module.
[CX-2368]: https://artsyproduct.atlassian.net/browse/CX-2368?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add myCollectionComparableWorks context module

---

src/Schema/Events/Auction.ts
src/Schema/Events/ExperimentViewed.ts
src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts
src/Schema/Values/OwnerType.ts

This PR adds tracking events for the new /auction/id page

feat(auction): Add auction events

---

src/Schema/Events/index.ts

Adds missing `ExperimentViewed` in Event type

chore: add ExperimentViewed to events

---

src/Schema/Events/Tap.ts
src/Schema/Events/index.ts

This PR resolves [CX-2415]
[CX-2415]: https://artsyproduct.atlassian.net/browse/CX-2415?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add tapped skip event

---

src/Schema/Values/OwnerType.ts

Add `OwnerType.savedSearch` and `OwnerType.savedSearches` to `PageOwnerType`

chore: add saved search/-es to PageOwnerType

---

src/Schema/Values/ContextModule.ts

The type of this PR is: ** Enhancement**
This PR resolves [CX-2457]
Added myCollectionArtworkAbout context module
[CX-2457]: https://artsyproduct.atlassian.net/browse/CX-2457?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(CX-2457): added myCollectionArtworkAbout context module

---

src/Schema/Values/ContextModule.ts

Add artworkRecommendationsRail context module.

feat: Add artworkRecommendationsRail context module

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

This PR resolves [TX-227]
The payment checkout flow will change in order to add the new payment method. Therefore, we want to track clicks on the page to understand better user behaviour.
Details are described [here](https://docs.google.com/spreadsheets/d/1mEwdJ71ts-MtY7vHKzCMPAePnC_OnlpL3i4VfwTpQjI/edit?usp=sharing)
[TX-227]: https://artsyproduct.atlassian.net/browse/TX-227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[TX-227] Creating events for the payment checkout flow

---

src/Schema/Events/Auction.ts
src/Schema/Events/index.ts

Adds auctionPageView and documentation

---

src/Schema/Events/MyCollection.ts

This PR resolves [CX-2610]
I used different type in eigen
[CX-2610]: https://artsyproduct.atlassian.net/browse/CX-2610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove context_screen from TappedRequestPriceEstimate interfase

---

src/Schema/Events/MyCollection.ts

The type of this PR is: **FIX**
forgot to push the changes of the example
apologies for spam
-_-' I hope now it works

fix example

---

src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts

In this commit was added a new interface ```SentRequestPriceEstimate```, ActionType ```sentRequestPriceEstimate``` and done some minor refactoring

feat: add SentRequestPriceEstimate interface, small ref

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

Supports https://github.com/artsy/force/pull/10353
@bbaiyr This is how we add the format of new events to track!

Partner url click

---

src/Schema/Values/ContextModule.ts

This PR resolves [GRO-1153]
Adding missing onboarding flow context module: `context_module: ContextModule.onboardingFlow` per this onboarding analytics spreadsheet here -->
https://docs.google.com/spreadsheets/d/12wj1rt-j5SguboPJMuaM1GqJD-5B5u5piipw8MQ5Zuk/edit?pli=1#gid=275928850
[GRO-1153]: https://artsyproduct.atlassian.net/browse/GRO-1153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(onboarding): add context module for onboarding follows and saves

---

src/Schema/Values/OwnerType.ts

- include myCollectionInsightsMedianAuctionPrice in ScreenOwnerType

include myCollectionInsightsMedianAuctionPrice in ScreenOwnerType

---

src/Schema/Events/Video.ts
src/Schema/Events/index.ts

Adds viewedVideo event

---

src/Schema/Events/Click.ts

The type of this PR is: **Bugfix**
This PR resolves []
This PR just updates the name of a parameter from `expended` (typo) to `expanded`

fix: update param name typo

---

src/Schema/Values/ContextModule.ts

This PR resolves [-]
Expand AuthContextModule type - add ContextModule.myCollectionHome

feat: expand AuthContextModule type

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

Track click on download order summary in CMS

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

This PR resolves [PX-5361]
This PR adds a new event to Cohesion to utilize in Volt for [PX-5307].
[PX-5361]: https://artsyproduct.atlassian.net/browse/PX-5361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PX-5307]: https://artsyproduct.atlassian.net/browse/PX-5307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore:add event for clicked on price display

---

src/Schema/Events/Authentication.ts

Adds `"scroll"` to the `AuthTrigger` union to more accurately track triggers in Force.

feat(auth): adds scroll to auth trigger

---

src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

Addresses [CX-3317]
Add events for new MyC web uploading flow.
[CX-3317]: https://artsyproduct.atlassian.net/browse/CX-3317?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add events for new MyC web uploading flow

---

src/Schema/Events/MyCollection.ts

Adjsut new My Collection event owner type.

fix: Adjsut new My Collection event owner type

---

src/Schema/Events/MyCollection.ts

Adjsut new My Collection event keys.

fix: Adjust new My Collection event keys

---

src/Schema/Events/ExperimentViewed.ts

Add context module to ExperimentViewed.

chore: add context module to ExperimentViewed

---

src/Schema/Events/ExperimentViewed.ts

This PR adds  `context owner screen`  to ExperimentViewed

chore: add context owner screen  to ExperimentViewed

---

src/Schema/Events/Click.ts
src/Schema/Events/ExperimentViewed.ts
src/Schema/Events/Tap.ts

Add missing fields to ExperimentViewed

chore: add missing fields to ExperimentViewed

---

src/Schema/Values/ContextModule.ts

This PR resolves [CX-3356]
This PR adds the upcoming auction results rail context modules.
**Bonus:** I alphabetically sorted the context modules
[CX-3356]: https://artsyproduct.atlassian.net/browse/CX-3356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add upcoming auctions results rail

---

src/Schema/Values/ContextModule.ts

This PR resolves [CX-3356]
Add curatedTrendingArtistsRail context module
[CX-3356]: https://artsyproduct.atlassian.net/browse/CX-3356?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: add curatedTrendingArtistsRail context module

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

Add curatorPicksRail context module.

feat: Add curatorPicksRail context module

---

src/Schema/Values/OwnerType.ts

Add recentlyViewed owner type.

feat: Add recentlyViewed owner type

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

This PR partially resolves [PX-5429]
This PR adds a new event to Cohesion to enable the completion of Volt work as part of [PX-5429]
[PX-5429]: https://artsyproduct.atlassian.net/browse/PX-5429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PX-5429]: https://artsyproduct.atlassian.net/browse/PX-5429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: PX-5429 adding new events for BN and MO

---

src/Schema/Values/OwnerType.ts

ADd recentlyViewed to screen owner type.

feat: ADd recentlyViewed to screen owner type

---

src/Schema/Events/ImpressionTracking.ts
src/Schema/Events/index.ts

schema here
https://docs.google.com/spreadsheets/d/12wj1rt-j5SguboPJMuaM1GqJD-5B5u5piipw8MQ5Zuk/edit#gid=2106077522

Adds tooltipViewed for progressive onboarding

---

src/Schema/Values/OwnerType.ts

Add newWorksFromGalleriesYouFollow screen owner type.

feat: Add newWorksFromGalleriesYouFollow screen owner type

---

src/Schema/Values/OwnerType.ts

Add similarToRecentlyViewed screen owner type.

feat: Add similarToRecentlyViewed screen owner type

---

src/Schema/Values/OwnerType.ts

The type of this PR is: **Fix**
Move similarToRecentlyViewed to ScreenOwnerType

fix: Move similarToRecentlyViewed to ScreenOwnerType

---

src/Schema/Events/Search.ts
src/Schema/Events/index.ts

This PR resolves [FX-4629](https://artsyproduct.atlassian.net/browse/FX-4629)
Follow-up to https://github.com/artsy/cohesion/pull/411
[FX-4629]: https://artsyproduct.atlassian.net/browse/FX-4629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: update SelectedSearchSuggestionQuickNavigationItem event

---

src/Schema/Events/MyCollection.ts

Addresses [CX-3611]
Add artist ID to SaveCollectedArtwork event.
[CX-3611]: https://artsyproduct.atlassian.net/browse/CX-3611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add artist ID to SaveCollectedArtwork event

---

src/Schema/Values/OwnerType.ts

Addresses [CX-3597]
Add price database screen owner type.
[CX-3597]: https://artsyproduct.atlassian.net/browse/CX-3597?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add price database screen owner type

---

src/Schema/Events/MyCollection.ts
src/Schema/Values/OwnerType.ts

Addresses [CX-3611]
Add is_p1_artist to SaveCollectedArtwork event.
[CX-3611]: https://artsyproduct.atlassian.net/browse/CX-3611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: Add is_p1_artist to SaveCollectedArtwork event

---

src/Schema/Events/ImpressionTracking.ts
src/Schema/Events/index.ts

@iskounen Let me know if this works!

Event to track errors

---

src/Schema/Values/OwnerType.ts

Addresses [CX-3685]
Add galleriesForYou screen owner type.
[CX-3685]: https://artsyproduct.atlassian.net/browse/CX-3685?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add galleriesForYou screen owner type

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

Tracking for CMS alerts!
I added some more generic events for Nav bar clicks and upload artworks that can be re-used elsewhere.

CMS alerts events tracking

---

src/Schema/Events/index.ts

The type of this PR is: **FIX**
[Slack thread](https://artsy.slack.com/archives/C02BC3HEJ/p1693410047157529)
Relates to https://github.com/artsy/cohesion/pull/448
Fixes issues that are leading the build to fail

fix: saved alerts events

---

src/DeprecatedHelpers/Click/ClickedEntityGroup.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

Addresses [ONYX-48]
Force PR: https://github.com/artsy/force/pull/12819
Add `newWorksByGalleriesYouFollowRail` to auth context modules and ClickedEntityGroup.
[ONYX-48]: https://artsyproduct.atlassian.net/browse/ONYX-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add newWorksByGalleriesYouFollowRail to auth context modules

---

src/Schema/Events/ImpressionTracking.ts
src/Schema/Values/OwnerType.ts

This PR resolves [AMBER-145]
This updates the `OwnerType` with a new `demand` field. 
[AMBER-145]: https://artsyproduct.atlassian.net/browse/AMBER-145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(demand): Add OwnerType.demand

---

src/Schema/Values/ContextModule.ts

Addresses [ONYX-45]
Add galleriesNearYouRail context module.
[ONYX-45]: https://artsyproduct.atlassian.net/browse/ONYX-45?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add galleriesNearYouRail context module

---

src/Schema/Values/ContextModule.ts

This PR resolves [ONYX-295]
This PR adds the right context module that is required to track taps on the create alert button in the footer of artist artworks grid.
[ONYX-295]: https://artsyproduct.atlassian.net/browse/ONYX-295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add artistArtworksGridEnd

---

src/Schema/Events/index.ts

This PR resolves [ONYX-307]
This PR adds the action type required to track taps on Create Alert info button
[ONYX-307]: https://artsyproduct.atlassian.net/browse/ONYX-307?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: added tappedCreateAlertHeader action type

---

src/DeprecatedHelpers/Tap/TappedEntityGroup.ts
src/Schema/Events/Tap.ts
src/Schema/Events/index.ts

Addresses [ONYX-296]
Follow-Up PR for https://github.com/artsy/cohesion/pull/459
Add activities to TappedEntityDestinationType.
[ONYX-296]: https://artsyproduct.atlassian.net/browse/ONYX-296?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: Add activities to TappedEntityDestinationType

---

src/Schema/Values/OwnerType.ts

Adds `lotsByArtistsYouFollow` on `OwnerType` enum to start tracking page views of the `Lots By Artists You Follow` screen in the app.
Slack thread for more context -> [here](https://artsy.slack.com/archives/C03NF9TKR/p1695820375843259)
Eigen PR -> [here](https://github.com/artsy/eigen/pull/9360)

feat: add lotsByArtistsYouFollow

---

src/Schema/Values/OwnerType.ts

Adds  `lotsByArtistsYouFollow` to `ScreenOwnerType` export as well (followup to https://github.com/artsy/cohesion/pull/463)

fix: lotsByArtistsYouFollow

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

Demand 1.1 tracking

---

src/Schema/Values/ContextModule.ts

[Context](https://github.com/artsy/force/blob/3f94d6cd4bf549d92bed8314ed8d04f8c884ed0d/src/Components/Alert/Hooks/useAlert.tsx#L45)
Add createAlert to AuthContextModule.

chore: Add createAlert to AuthContextModule

---

src/Schema/Values/OwnerType.ts

Add OwnerType.alertConfirmation to PageOwnerType

add OwnerType.alertConfirmation to PageOwnerType

---

src/Schema/Events/Search.ts
src/Schema/Values/OwnerType.ts

Sorry for the mess!
I couldn't figure out how to upgrade the version number without using the Version label. I need some changes from the previous PRs. Those PRs had Version label Trivial which led to not changing the version number

PR to update the version number

---

src/Schema/Events/Click.ts
src/Schema/Events/ImpressionTracking.ts
src/Schema/Events/index.ts
src/Schema/Values/OwnerType.ts

This PR resolves [AS-4346]
Creating events to track partners offers in CMS
[details](https://docs.google.com/spreadsheets/d/1c65vugkF2C4YuXwBXno8aqsBh4B2fTwxiLmgY_MhjWc/edit#gid=1515896528)
[AS-4346]: https://artsyproduct.atlassian.net/browse/AS-4346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AS-4346] Adding new events for partners offers

---

src/Schema/Values/OwnerType.ts

https://artsyproduct.atlassian.net/browse/ONYX-625
Add page and screen owner types for the new notifications/notification screen and page

feat: Add page and screen owner types for activities and activity

---

.vscode/settings.json
src/Schema/Events/Click.ts
src/Schema/Events/ImpressionTracking.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

This PR adds the required types to implement tracking events on the recently viewed screen.
**Note:** For easier review, I suggest to **_hide white spaces_**

feat: add selected suggested filter event

---

src/Schema/Events/Click.ts
src/Schema/Events/Tap.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

This PR resolves [[EMI-1783](https://artsyproduct.atlassian.net/browse/EMI-1783)]
[EMI-1783]: https://artsyproduct.atlassian.net/browse/EMI-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AS-4497] Adding tracking to notification page

---

src/Schema/Events/Click.ts
src/Schema/Events/Tap.ts

This PR resolves [[EMI-1783](https://artsyproduct.atlassian.net/browse/EMI-1783)]
[EMI-1783]: https://artsyproduct.atlassian.net/browse/EMI-1783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix artwork view event

---

src/Schema/Events/Tap.ts

This PR resolves [EMI-1829]
[EMI-1829]: https://artsyproduct.atlassian.net/browse/EMI-1829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[AS-4497] Add flow to tapped buy now

---

src/Schema/Events/Click.ts
src/Schema/Events/Tap.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

This PR resolves [ONYX-907]
Add missing auth context modules - these are required to track clicks on the sell page
[ONYX-907]: https://artsyproduct.atlassian.net/browse/ONYX-907?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add missing auth context

---

src/Schema/Values/ContextModule.ts

This PR resolves [DIA-640]
Add `newWorksForYouRail` to the AuthContextModule.
[DIA-640]: https://artsyproduct.atlassian.net/browse/DIA-640?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

chore: add newWorksForYouRail to auth context modules

---

src/Schema/Values/ContextModule.ts

The type of this PR is: Fix
This PR resolves [ONYX-969](https://artsyproduct.atlassian.net/browse/ONYX-969)
Add lotsForYouRail and topAuctionLotsRail to AuthContextModule.
[ONYX-969]: https://artsyproduct.atlassian.net/browse/ONYX-969?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ONYX-969): add lotsForYouRail, topAuctionLotsRail to AuthContextModule

---

src/Schema/Events/Click.ts
src/Schema/Events/index.ts

Re: [DIA-679](https://artsyproduct.atlassian.net/browse/DIA-679)
[DIA-679]: https://artsyproduct.atlassian.net/browse/DIA-679?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: adds events for conversation history

---

src/DeprecatedSchema/DeprecatedValues.ts

Supports the new "What's New" section of the nav.

feat: adds whats new context module

---

src/Schema/Events/index.ts

adding the export to redshift for one of the events tracking in the post-inquiry flow for Collector profile

fix: adding export to redshift for TappedMyCollectionAddArtworkArtist

---

src/Schema/Values/ContextModule.ts

adding alertsAll to context module for demand2

chore: adding alertsAll to context module for demand2

---

src/Schema/index.ts

Clients currently need to use an overly verbose import to access these event defintions.
For example:
```typescript
import { ClickedNotificationsBell } from "@artsy/cohesion/dist/Schema/Events/ActivityPanel"
```
This commit imports these events into the top-level package export.

chore: export Events/ActivityPanel

---

src/Schema/Values/OwnerType.ts

- chore: add artistArticles ScreenOwnerType

chore: add artistArticles ScreenOwnerType

---

src/Schema/Events/Authentication.ts

This PR adds "tap" to the `AuthTrigger` type so that we can start tracking `AuthImpression` events from Eigen.

feat(DIA-815): added "tap" to AuthTrigger

---

src/Schema/Events/ImpressionTracking.ts
src/Schema/Events/Tap.ts

The type of this PR is: **FIX**

fix: typo error

---

src/Schema/Values/ContextModule.ts

This PR adds a context module for the auction registration form, building from work in https://github.com/artsy/force/pull/13378.

chore(EMI-2159): add context module for auction registration

---

src/Schema/Values/ContextModule.ts

Add missing context module to track ONYX-1459

feat: add artistArtworksCreateAlertPromptMessage context module

---

src/Schema/Values/ContextModule.ts
src/Schema/Values/OwnerType.ts

This PR resolves [ONYX-1489]
- add ContextModule and OwnerType quickLinks
- sort lists alphabetically 
[ONYX-1489]: https://artsyproduct.atlassian.net/browse/ONYX-1489?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat(ONYX-1489): add ContextModule and OwnerType quickLinks

---

src/Schema/Values/ContextModule.ts

add artistArtworksCreateAlertRemindertMessage
removing artistArtworksCreateAlertPromptMessage as it will no longer be used and the PR i used it for was closed

chore: add artistArtworksCreateAlertRemindertMessage

---

src/Schema/Values/ContextModule.ts

chore: fix typo

---

src/DeprecatedHelpers/Tap/__tests__/TappedTabBar.test.ts
src/Schema/Values/Tab.ts

This PR adds favorites as a tab

chore: add favorites as tab type

---

src/Schema/Values/OwnerType.ts

chore: add favorites as owner type

---

src/Schema/Values/OwnerType.ts

This PR addresses [ONYX-1580](https://artsyproduct.atlassian.net/browse/ONYX-1580).
Adding tracking support for the following screens:
- Account
- Account Settings
- Email
- Phone Number
- Price Range
- Password
- Delete My Account
- Payment
- Add Payment
- Push Notifications
- Personal Data Request
- Dark Mode
- About
- Order History (or Orders)
| Screen Name | Screenshot |
|--------|--------|
| Account | <img src="https://github.com/user-attachments/assets/a44abb40-a8fd-489b-84af-9a974902d443" alt="signal-2025-03-19-160321_015" height="300"/> |
| Account Settings | <img src="https://github.com/user-attachments/assets/efb8d40d-d0d0-4dfd-9f4b-30e912e5e433" alt="signal-2025-03-19-160321_013" height="300"/> | 
| Email | <img …

feat: add new OwnerType values to track existing account/settings screens

---

src/Schema/CMS/Events/ArtworkFilter.ts

The type of this PR is: **Fix**
Quick fix for a misnamed interface

fix(artwork-filter): fix prop

---

src/Schema/Values/OwnerType.ts

This PR adds `collect` as an ownertype

chore: add collect screen owner type

---

src/Schema/Events/Settings.ts
src/Schema/Events/index.ts

* Eigen PR: https://github.com/artsy/eigen/pull/12053
* 
Add DarkModeOptionUpdated event.

chore: Add DarkModeOptionUpdated event

---

src/Schema/Events/MyCollection.ts
src/Schema/Events/index.ts

Add missing events for new profile and myc
- add TappedMyCollection interface
https://artsy.slack.com/archives/C05EQL4R5N0/p1747082377247229?thread_ts=1746812579.717129&cid=C05EQL4R5N0

feat: add missing events for new profile and myc - TappedMyCollection interface

---

src/Schema/CMS/Events/ShowFlow.ts
src/Schema/CMS/Events/index.ts
src/Schema/CMS/Values/CmsContextModule.ts

This adds CMS Show events from the spreadsheet [here](https://docs.google.com/spreadsheets/d/1m19FPaEV8OUK4_-nHEc6Eu-yBhknQSFDPILz1N1icUE/edit?gid=0#gid=0)
cc @artsy/amber-devs

feat(show): Add CMS Show events

---

src/Schema/CMS/Events/BulkEditFlow.ts

The type of this PR is: **FIX**
Small improvement, adjust how we handle "number" values in the CMS Bulk edit events
Adds more consistent typing for number typed values, we have a mix of string and number usage 
cc @artsy/amber-devs

fix(bulk-edits): Adds more consistent typing for number typed values

---

src/Schema/Events/Tap.ts
src/Schema/Events/index.ts
src/Schema/Values/ContextModule.ts

This PR adds the required events for the price range onboarding.

chore: add price range onboarding events

---

src/Schema/CMS/Events/AnalyticsPage.ts

Thank you Leandro for noticing discrepancies here and the [spreadsheet](https://docs.google.com/spreadsheets/d/1KPwzjTQDk0rNCqBMUK-2NopS6ZOsKmmlYOGBXcJTrZA/edit?gid=0#gid=0). This unlocks the `tooltip` event from `contextModule.mostViewed`, since we have tooltips in multiple sections. It also locks the `contextModule.mostViewed` for the correct event, and updates the examples.

chore: Analytics CMS fixes

---

src/Schema/CMS/Events/AnalyticsPage.ts

Adds `horizontal_bar` to example graph types, because we are adding it with V1 of analtyics.

chore: Add horizontal_bar to graph types

---

src/Schema/CMS/Events/AnalyticsPage.ts

Adds `vertical_bar` as a string graph type for CMS Analytics

chore: add vertical bar example
